version: '3.3'

services:
  db:
   image: mysql:5.7
   volumes:
    - db_data:/var/lib/mysql
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: password_root
    MYSQL_DATABASE: wordpress
    MYSQL_USER: matheus
    MYSQL_PASSWORD: secret
  wordpress:
   depends_on:
    -db
   image: wordpress:latest
   ports:
    -"8000:80"
   restart: always
   en